spring.application.name=file-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://${discovery.host}:${discovery.port}/eureka/
#Jpa
spring.datasource.url=jdbc:postgresql://${file.datasource.host}:${file.datasource.port}/${file.datasource.database}
spring.datasource.username=${file.datasource.username}
spring.datasource.password=${file.datasource.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.crm.file=DEBUG
#App
#Max size of file in bytes
app.file.max-size=15728640
app.avatars.max-size=5000000
spring.servlet.multipart.max-file-size=36MB
spring.servlet.multipart.max-request-size=36MB