spring.application.name=file-service
server.port=0
#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#Jpa
spring.datasource.url=jdbc:postgresql://localhost:5433/FileDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.crm.file=DEBUG